import ts from "typescript";
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
const roots = [
  "src",
  "individual/core",
  "individual/service",
  "individual/companion/src",
  "individual/extension/src",
  "vscode-extension/src",
  "desktop/electron",
  "desktop/renderer/src",
  "scripts",
  "tests",
];
async function files(root: string): Promise<string[]> {
  const result: string[] = [];
  for (const entry of await readdir(root, { withFileTypes: true })) {
    const p = path.join(root, entry.name);
    if (entry.isDirectory()) result.push(...(await files(p)));
    else if (p.endsWith(".ts") || p.endsWith(".tsx")) result.push(p);
  }
  return result;
}
let output =
  "# Code reference\n\nGenerated by `npm run docs:code` from the TypeScript AST. The README explains module responsibilities; this index lists declarations and class methods in every authored TypeScript file. Signatures may be inferred by TypeScript; open the linked source for implementation.\n";
for (const file of (await Promise.all(roots.map(files))).flat().sort()) {
  const text = await readFile(file, "utf8"),
    source = ts.createSourceFile(
      file,
      text,
      ts.ScriptTarget.Latest,
      true,
      file.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
    ),
    relative = file.replaceAll("\\", "/");
  const symbols: { name: string; kind: string; line: number }[] = [];
  for (const node of source.statements) {
    const line = source.getLineAndCharacterOfPosition(node.getStart()).line + 1;
    if (ts.isClassDeclaration(node)) {
      symbols.push({
        name: node.name?.text ?? "(anonymous)",
        kind: "class",
        line,
      });
      for (const member of node.members)
        if (
          ts.isMethodDeclaration(member) ||
          ts.isConstructorDeclaration(member)
        )
          symbols.push({
            name: `${node.name?.text}.${ts.isConstructorDeclaration(member) ? "constructor" : member.name?.getText(source)}`,
            kind: "method",
            line:
              source.getLineAndCharacterOfPosition(member.getStart()).line + 1,
          });
    } else if (ts.isFunctionDeclaration(node))
      symbols.push({
        name: node.name?.text ?? "(anonymous)",
        kind: "function",
        line,
      });
    else if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node))
      symbols.push({
        name: node.name.text,
        kind: ts.isInterfaceDeclaration(node) ? "interface" : "type",
        line,
      });
    else if (ts.isVariableStatement(node))
      for (const decl of node.declarationList.declarations)
        symbols.push({
          name: decl.name.getText(source),
          kind: "binding / schema",
          line,
        });
  }
  output += `\n## ${relative}\n\n[Open source](../${relative})\n\n`;
  if (symbols.length)
    output +=
      "| Declaration | Kind | Line |\n| --- | --- | --- |\n" +
      symbols
        .map(
          (s) =>
            `| \`${s.name.replaceAll("|", "\\|")}\` | ${s.kind} | ${s.line} |`,
        )
        .join("\n") +
      "\n";
  else
    output +=
      "Top-level integration tests or command registrations; see source.\n";
}
await mkdir("docs", { recursive: true });
await writeFile("docs/CODE_REFERENCE.md", output);
console.log("Generated docs/CODE_REFERENCE.md");
